# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# REDEFINE 主题配置文件 V2
# 作者：EVANNOTFOUND
# GITHUB: https://github.com/EvanNotFound/hexo-theme-redefine
# 文档：https://redefine-docs.ohevan.com
# 演示：https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 基本信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/info
info:
  # 网站标题
  title: 王二的博客
  # 作者名称
  author: wanger
  # 网站 URL
  url: https://10knamesmore.github.io
# 基本信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标
  favicon: /images/redefine-favicon.svg
  # 网站 Logo
  logo:
  # 网站头像
  avatar: /images/mutsmi.jpg
  # 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 颜色 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色调
  primary: "#A31F34"
  # 次要颜色（待定）
  secondary:
  # 默认主题模式初始值（将被 prefer-color-scheme 覆盖）
  default_mode: dark # light（浅色）, dark（深色）
# 颜色 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 网站自定义 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义字体
  fonts:
    # 中文字体
    chinese:
      enable: true # 是否启用自定义中文字体
      family: # 字体族
      url: # 字体 CSS 文件 URL
    # 英文字体
    english:
      enable: false # 是否启用自定义英文字体
      family: # 字体族
      url: # 字体 CSS 文件 URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: true # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: true # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器 API URL（无需更改）
    enable: true # 是否启用网站计数器
    site_pv: true # 网站浏览量
    site_uv: true # 网站访客数
    post_pv: true # 文章浏览量
  # 是否启用单页面体验（使用 swup）。参见 https://swup.js.org/。类似于 pjax
  single_page: true
  # 是否启用预加载器
  preloader: false
  # 是否启用 Open Graph
  open_graph: true
  side_tools:
    auto_expand: true
  # Google Analytics 分析
  google_analytics:
    enable: false # 是否启用 Google Analytics
    id: # Google Analytics 测量 ID
# 网站自定义 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# FONTAWESOME 图标 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro v6.2.1
  # 细体版本
  thin: false
  # 轻量版本
  light: false
  # 双色版本
  duotone: false
  # 锐利实心版本
  sharp_solid: false
# FONTAWESOME 图标 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # static（静态）或 fixed（固定）
  # 首页横幅图片
  image:
    light: images/background.jpg # 浅色模式
    dark: images/background.jpg # 深色模式
  # 首页横幅标题
  title: 或者也叫wanger
  # 首页横幅副标题
  subtitle:
    text: ["会写点东西,发些照片", "保持更新(maybe)"] # 副标题文本，数组
    hitokoto: # 一言配置
      enable: false # 是否启用一言
      api: https://v1.hitokoto.cn # API URL，可添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 60 # 打字速度（毫秒）
    backing_speed: 50 # 退格速度（毫秒）
    starting_delay: 500 # 开始延迟（毫秒）
    backing_delay: 1500 # 退格延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true # 是否智能退格
  # 首页横幅文本颜色
  text_color:
    light: "#fff" # 浅色模式
    dark: "#d1d1b6" # 深色模式
  # 文本的具体样式
  text_style:
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题和副标题之间的行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font:
    # 是否启用自定义字体
    enable: false
    # 字体族
    family:
    # 字体 CSS 文件 URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接样式
    style: default # default（默认）、reverse（反转）、center（居中）
    # 社交链接
    links:
      github: https://github.com/10knamesmore # 你的 GitHub URL
      bilibili: https://space.bilibili.com/74184478?spm_id_from=333.337.0.0
      instagram: # 你的 Instagram URL
      zhihu: # 你的知乎 URL
      twitter: # 你的 Twitter URL
      email: # 你的邮箱
      # ...... # 你可以添加更多
    # 带二维码抽屉的社交链接
    qrs:
      weixin: # 你的微信二维码图片 URL
      # ...... # 你可以添加更多
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: true
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧
    right: "#367df7" # 右侧
    transparency: 35 # 透明度百分比（10-99）
  # 导航栏宽度（通常无需修改）
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 导航栏链接
  links:
    Home:
      path: /
      icon: fa-solid fa-house # 可以为空
    # Archives:
    #   path: /archives
    #   icon: fa-solid fa-archive # 可以为空
    # Status:
    #   path: https://status.ohevan.com/
    #   icon: fa-solid fa-chart-bar
    About:
      icon: fa-solid fa-user
      submenus:
        Github: https://github.com/10knamesmore
        # Blog: #
        # Friends: /friends
    相册:
      icon: fa-solid fa-image
      path: /gallery

    # Links:
    #   icon: fa-regular fa-link
    #   submenus:
    #     Link1: /link1
    #     Link2: /link2
    #     Link3: /link3
    # ...... # 你可以添加更多
  # 导航栏搜索（本地搜索）。需要 hexo-generator-searchdb（npm i hexo-generator-searchdb）。参见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: true
    # 页面加载时预加载搜索数据
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 侧边栏位置。left（左）、right（右）
    first_item: menu # 侧边栏第一项。menu（菜单）、info（信息）
    announcement: # 公告文本
    show_on_mobile: true # 是否在移动端弹出菜单中显示侧边栏导航
    links:
      # Archives:
      #   path: /archives
      #   icon: fa-regular fa-archive # 可以为空
      # Tags:
      #   path: /tags
      #   icon: fa-regular fa-tags # 可以为空
      # Categories:
      #   path: /categories
      #   icon: fa-regular fa-folder # 可以为空
      # ...... # 你可以添加更多
  # 文章日期格式
  article_date_format: auto # auto（自动）、relative（相对）、YYYY-MM-DD、YYYY-MM-DD HH:mm:ss 等
  # 文章分类可见性
  categories:
    enable: true # 是否启用
    limit: 3 # 显示的最大分类数量
  # 文章标签可见性
  tags:
    enable: true # 是否启用
    limit: 3 # 显示的最大标签数量
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/posts/articles
articles:
  # 设置文章的样式
  style:
    font_size: 16px # 字体大小
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片圆角半径
    image_alignment: center # 图片对齐方式。left（左）、center（居中）
    image_caption: false # 是否显示图片标题
    link_icon: true # 是否显示链接图标
    title_alignment: left # 标题对齐方式。left（左）、center（居中）
    headings_top_spacing: # h1-h6 标题顶部间距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计。需要 hexo-wordcount（npm install hexo-wordcount）。参见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数统计
    min2read: true # 是否显示阅读时间
  # 作者标签
  author_label:
    enable: true # 是否启用
    auto: false # 是否自动添加作者标签，如 Lv1、Lv2、Lv3...
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否启用代码块复制按钮
    style: mac # mac（Mac 风格）| simple（简洁）
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体族
      url: # 字体 CSS 文件 URL
  # 目录设置
  toc:
    enable: true # 是否启用目录
    max_depth: 3 # 目录深度
    number: false # 是否自动为目录添加编号
    expand: true # 是否展开目录
    init_open: true # 默认打开目录
  # 是否启用版权声明
  copyright:
    enable: true # 是否启用
    default: cc_by_nc_sa # 默认许可证，可以是 cc_by_nc_sa、cc_by_nd、cc_by_nc、cc_by_sa、cc_by、all_rights_reserved、public_domain
  # 是否为图片启用懒加载
  lazyload: true
  # 文章推荐。需要 nodejieba（npm install nodejieba）。移植自 hexo-theme-volantis。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 显示的最大文章数量
    limit: 3
    # 移动端显示的最大文章数量
    mobile_limit: 2
    # 占位图片
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过的目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: true
  # 评论系统
  system: waline # waline、gitalk、twikoo、giscus
  # 系统配置
  config:
    # Waline 评论系统。参见 https://waline.js.org/
    waline:
      serverUrl: https://waline-test-7j71t1lc9-10knamesmores-projects.vercel.app/ # Waline 服务器 URL。例如 https://example.example.com
      lang: zh-CN # Waline 语言。例如 zh-CN、en-US。参见 https://waline.js.org/guide/client/i18n.html
      emoji: [
          https://unpkg.com/@waline/emojis@1.2.0/qq,
          https://unpkg.com/@waline/emojis@1.2.0/bmoji,
          https://unpkg.com/@waline/emojis@1.2.0/alus,
          https://unpkg.com/@waline/emojis@1.2.0/tw-emoji,
        ] # Waline 表情包，参见 https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: wasd # Google reCAPTCHA v3 密钥。参见 https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile 密钥。参见 https://waline.js.org/reference/client/props.html#turnstilekey
      reaction: true # Waline 反应。参见 https://waline.js.org/reference/client/props.html#reaction
    # Gitalk 评论系统。参见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: Ov23lidWVOnlJXBRpPA5 # GitHub 应用客户端 ID
      clientSecret: 36ec87dd088839bc9d04793723285c5e529b8e75 # GitHub 应用客户端密钥
      repo: myBlogComments # GitHub 仓库
      owner: 10knamesmore # GitHub 仓库所有者
      proxy: # GitHub 仓库代理
    # Twikoo 评论系统。参见 https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo 版本，如果不知道是什么请不要修改
      server_url: # Twikoo 服务器 URL。例如 https://example.example.com
      region: # Twikoo 地区。可以为空
    # Giscus 评论系统。参见 https://giscus.app/
    giscus:
      repo: # Github 仓库名称，例如 EvanNotFound/hexo-theme-redefine
      repo_id: # Github 仓库 ID
      category: # Github 讨论分类
      category_id: # Github 讨论分类 ID
      mapping: pathname # 用作页面唯一标识符的值。例如 pathname、url、title、og:title。不要在启用 PJAX 时使用 og:title，因为 pjax 在页面更改时不会更新 og:title
      strict: 0 # 是否启用严格模式。例如 0、1
      reactions_enabled: 1 # 是否启用反应。例如 0、1
      emit_metadata: 0 # 是否发出元数据。例如 0、1
      lang: en # Giscus 语言。例如 en、zh-CN、zh-TW
      input_position: bottom # 评论框放置在评论上方/下方。例如 top（上）、bottom（下）
      loading: lazy # 延迟加载评论
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/footer
footer:
  # 显示网站运行时间
  runtime: true # 是否显示网站运行时间
  # 页脚图标，在此填写 fontawesome 图标代码
  icon: '<i class="fa-solid fa-skull-crossbones fa-bounce" color: #f54545"></i>'
  # 网站开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2024/8/27 17:00:00
  # 网站统计
  statistics: true # 是否显示网站统计（总文章数、总字数）
  # 页脚消息
  customize: 你说得对,但是
  # ICP 备案号。参见 https://beian.miit.gov.cn/
  icp:
    enable: false # 是否启用
    number: # ICP 备案号
    url: # ICP 备案链接
# 页脚 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: false
  # 注入自定义头部 HTML 代码
  head:
    -
    -
  # 注入自定义页脚 HTML 代码
  footer:
    -
    -
# 注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS 订阅。需要 hexo-generator-feed（npm i hexo-generator-feed）。参见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # 是否启用
  # Aplayer 音乐播放器。参见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: false # 是否启用
    type: fixed # fixed（固定）、mini（迷你）
    audios:
      - name: # 音频名称
        artist: # 音频艺术家
        url: # 音频 URL
        cover: # 音频封面 URL
        lrc: # 音频歌词
  #      - name: # 音频名称
  #        artist: # 音频艺术家
  #        url: # 音频 URL
  #        cover: # 音频封面 URL
  #        lrc: # 音频歌词
  # .... 你可以在此添加更多音频
  # Mermaid JS 图表。需要 hexo-filter-mermaid-diagrams（npm i hexo-filter-mermaid-diagrams）。参见 https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用 mermaid
    version: "9.3.0" # 默认 v9.3.0
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友情链接页面列数
  friends_column: 2
  # 标签页面样式
  tags_style: blur # blur（模糊）、cloud（云）
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# CDN 加速 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用 CDN
  enable: false
  # CDN 提供商
  provider: npmmirror # npmmirror、zstatic、sustech、staticfile、bootcdn、cdnjs、jsdelivr、unpkg、custom（自定义）
  # 自定义 CDN URL
  # 格式示例：https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # ${path} 必须指向主题 "source" 文件夹的根目录
  custom_url:
# CDN 加速 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式（仅适用于想要修改主题源代码的开发者，不适用于普通用户）
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
